robotis_manipulator_h:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  # Position Controllers ---------------------------------------
  joint1_position:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 6000, i: 0.01, d: 0.1}

  joint2_position:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 6000, i: 0.01, d: 100.0}

  joint3_position:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 6000, i: 0.01, d: 80.0}
