robotis_manipulator_h:
 # Publish all joint states -----------------------------------
 joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 125

 arm1_controller:
   type: "effort_controllers/JointTrajectoryController"
   joints:
     - joint1
     - joint2
     - joint3


   gains: # Required because we're controlling an effort interface
     joint1: {p: 6000,  d: 0.1 , i: 0.01, i_clamp: 1}
     joint2: {p: 6000,  d: 100, i: 0.01, i_clamp: 1}
     joint3: {p: 6000,  d: 80, i: 0.01, i_clamp: 1}
